
import "./globals.css";
import StyledComponentsRegistry from "@/lib/registry";
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        <StyledComponentsRegistry><main>{children}</main></StyledComponentsRegistry>
      </body>
    </html>
  );
}
